fixes #460
publiclab/community-toolbox pull request #464
Opened 2021-05-02 21:04 UTC by swetshaw

fixes #460

2021-05-04 14:58 UTC, daemon1024 commented
Hi @swetshaw, Thanks for working on this. 

As I see, there's been already been approval at https://github.com/swetshaw/community-toolbox/pull/1 🎉 . It would be great if you could update the Pull Request Title here as well to something more descriptive.

Thanks Again 🥳

2021-05-11 09:14 UTC, swetshaw commented
Hi @daemon1024 , I have updated the Pull Request Title here. Please check if it looks good. Thankyou. :)

2021-11-29 06:21 UTC, TildaDares requested changes

2021-11-29 06:21 UTC, TildaDares commented on index.html
> ++                    <li><a class="line" href="#contributer">Contributors</a></li>
Hi @swetshaw, can you remove the extra plus sign you added to line 82? Thanks!

2022-03-01 10:09 UTC, merged

2022-03-01 10:10 UTC, TildaDares commented
Thank you @swetshaw!!